name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
        # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12.10-alpine 
        # Provide the password for postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: P@ssw0rd
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: install golang-migration
      run: |
           curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
           sudo mv migrate /usr/bin
           which migrate

    - name: Run migrations
    # make migrateup failed with make: *** No rule to make target 'migrateup'.  Stop.
    #  run: migrate -path db/migration -database "postgresql://root:P@ssw0rd@127.0.0.1:5432/simple_bank?sslmode=disable" -verbose up
      run: make migrateup
      
    - name: Test
    # go test -v -cover ./...
      run: make test